[package]
name = "sherlock-currency"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dirs = "6.0.0"
regex = "1.11.1"
serde = "1.0.218"
serde_json = "1.0.135"
surf = "2.3.2"
tokio = {version = "1.43.0", features=["full"]}
